// ═══════════════════ COMPLETE DATA ═══════════════════
const skills = [
  { id:"S-0001", name:"需求澄清访谈提纲生成", type:"skill", value:"把零散背景快速整理成可执行访谈提纲", stage:"调研/需求", tags:["调研","访谈"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    github:"https://github.com/anthropics/anthropic-quickstarts/tree/main/knowledge-work-plugins/design/skills/user-research",
    skillsSh:"user-research", installCmd:"claude skills add user-research",
    scene:"新产品/新功能立项前的用户访谈\n用户痛点挖掘与需求澄清\n竞品用户体验研究\n用户满意度与反馈收集",
    input:"【必填】\n- 研究目标：你想了解什么？解决什么问题？\n- 目标用户：访谈对象是谁？有什么特征？\n- 背景信息：已知的用户信息、产品现状\n\n【可选】\n- 假设：你对用户的初步假设是什么？\n- 限制：时间、人数、资源等约束",
    steps:"## 研究方法选择\n| 方法 | 适用场景 | 样本量 | 时间 |\n|-----|---------|-------|-----|\n| 用户访谈 | 深入了解需求和动机 | 5-8人 | 2-4周 |\n| 可用性测试 | 评估特定设计或流程 | 5-8人 | 1-2周 |\n| 问卷调查 | 量化态度和偏好 | 100+ | 1-2周 |\n| 卡片分类 | 信息架构决策 | 15-30人 | 1周 |\n\n## 访谈提纲结构\n1. 热身（5分钟）：建立融洽关系\n2. 背景了解（10分钟）：了解当前工作流程\n3. 深入探讨（20分钟）：针对具体话题深入挖掘\n4. 原型反馈（10分钟）：展示概念或原型\n5. 收尾（5分钟）：补充遗漏，致谢",
    outputTemplate:"## 研究计划\n- 研究目标\n- 研究方法\n- 时间线\n- 参与者招募标准\n\n## 访谈提纲\n- 开场白\n- 分主题问题列表\n- 追问 Probe\n- 活动安排\n\n## 综合报告\n- 关键发现主题\n- 用户语录\n- 洞察与机会点\n- 建议优先级",
    quality:"✓ 问题符合 MECE 原则（不重叠、不遗漏）\n✓ 每个问题有明确的研究目的\n✓ 包含开放式问题和追问\n✓ 避免引导性问题\n✓ 时间分配合理（总计 45-60 分钟）\n✓ 覆盖 warm-up、deep-dive、wrap-up 三阶段",
    boundary:"• 不适用于涉及敏感/合规风险的个人信息收集\n• 不替代专业用研人员的判断\n• 定量研究需要配合问卷/数据分析",
    example:"请帮我设计一份用户访谈提纲：\n\n【研究目标】了解用户在使用我们的电商 App 时的购物决策流程，以及影响他们下单的关键因素\n\n【目标用户】25-35 岁，近 3 个月内在 App 上有过购买行为的用户\n\n【背景信息】目前 App 的购物车放弃率较高（约 65%），想了解原因\n\n【假设】用户可能因为比价、运费、支付方式等原因放弃购买",
    faq:"Q: 访谈人数多少合适？\nA: 用户访谈通常 5-8 人即可发现 80% 以上的问题\n\nQ: 如何避免引导性问题？\nA: 使用 \"告诉我…\" \"描述一下…\" 而非 \"你是不是觉得…\"\n\nQ: 输入信息不够怎么办？\nA: 先补充研究目标和假设，输入越具体输出越有针对性"
  },
  { id:"S-0002", name:"用户旅程地图生成", type:"skill", value:"快速将用户场景转化为完整的用户旅程地图，识别痛点与机会点", stage:"调研/需求", tags:["交互设计","用户旅程","体验地图"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    github:"🔗 GitHub", skillsSh:"📦 skills.sh", installCmd:"npx skills add mastepanoski/claude-skills --skill ux-audit-rethink",
    scene:"梳理用户从接触产品到完成目标的全流程体验，识别关键触点和情绪波动",
    input:"【产品/功能】…\n【目标用户画像】…\n【核心场景】…\n【已知痛点】…\n【业务目标】…",
    steps:"1) 收集输入（产品信息/用户画像/场景）\n2) 拆解阶段（认知→考虑→使用→留存→推荐）\n3) 每阶段填充：用户行为/触点/情绪/痛点/机会点\n4) 标注关键 MOT（Moment of Truth）\n5) 输出可视化旅程地图 + 优先级排序的优化建议",
    outputTemplate:"【旅程地图】\n| 阶段 | 用户行为 | 触点 | 情绪 | 痛点 | 机会点 |\n…\n【关键 MOT】…\n【优化建议（按优先级）】…",
    quality:"阶段完整、触点可追溯、痛点有证据支撑、建议可执行", boundary:"不替代真实用户调研；基于假设的旅程需标注\"待验证\"", faq:"缺少用户画像时先用\"假设用户\"标注，后续用调研验证"
  },
  { id:"S-0003", name:"信息架构梳理与导航设计", type:"skill", value:"从功能列表或 PRD 快速生成结构化信息架构和导航方案", stage:"设计", tags:["交互设计","信息架构","导航"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    github:"🔗 GitHub", skillsSh:"📦 skills.sh", installCmd:"npx skills add mastepanoski/claude-skills --skill ux-audit-rethink",
    scene:"从一堆功能点或 PRD 组织成合理的页面层级和导航结构",
    input:"【产品类型】（B端/C端/后台…）\n【功能清单】…\n【用户角色】…\n【核心任务 Top3】…\n【参考竞品】…",
    steps:"1) 卡片分类：将功能按用户心智模型分组\n2) 确定层级：扁平 vs 深层，控制在 3 级以内\n3) 设计导航模式（Tab/侧边栏/面包屑组合）\n4) 绘制站点地图（Sitemap）\n5) 标注页面间跳转关系和快捷入口\n6) 输出导航方案 + 理由说明",
    outputTemplate:"【信息架构树】\n- L1: …\n  - L2: …\n    - L3: …\n【导航方案】…\n【设计决策说明】…",
    quality:"层级 ≤ 3 级、分组符合用户心智、核心任务 ≤ 3 步可达", boundary:"不做视觉稿；复杂B端系统建议配合卡片分类测试验证"
  },
  { id:"S-0004", name:"交互流程图与页面流设计", type:"skill", value:"将需求描述转化为完整的交互流程图，覆盖主流程和异常分支", stage:"设计", tags:["交互设计","流程图","页面流"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    github:"🔗 GitHub", skillsSh:"📦 skills.sh", installCmd:"npx skills add mastepanoski/claude-skills --skill cognitive-walkthrough",
    scene:"设计某个功能的完整交互流程，包含正常路径、异常处理和边界情况",
    input:"【功能名称】…\n【用户目标】…\n【前置条件】…\n【涉及角色】…\n【已知业务规则】…\n【需要考虑的异常】…",
    steps:"1) 明确起点和终点\n2) 绘制主流程（Happy Path）\n3) 补充分支：权限校验、输入校验、空状态、网络异常\n4) 标注每步的页面/组件和交互方式\n5) 检查闭环：所有分支最终都能回到正常状态或明确终止\n6) 输出流程图描述 + 页面清单",
    outputTemplate:"【主流程】\nStep1 → Step2 → … → 完成\n【分支流程】\n- 异常A：…\n- 异常B：…\n【页面清单】\n| 页面 | 功能 | 入口 | 出口 |\n【交互备注】…",
    quality:"主流程完整、异常覆盖率 ≥ 80%、每个分支有回归路径", boundary:"不做高保真原型；复杂流程建议分模块输出"
  },
  { id:"S-0005", name:"可用性启发式评估", type:"skill", value:"基于 Nielsen 十大原则对界面进行系统化可用性走查，输出问题清单和优化建议", stage:"评审/测试", tags:["交互设计","可用性","评估"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    github:"🔗 GitHub", skillsSh:"📦 skills.sh", installCmd:"npx skills add mastepanoski/claude-skills --skill nielsen-heuristics-audit",
    scene:"对已有设计稿或线上页面做可用性审查，发现体验问题",
    input:"【产品/页面名称】…\n【截图或描述】…\n【目标用户】…\n【核心任务】…\n【当前已知问题】…",
    steps:"1) 逐条对照 Nielsen 十大可用性原则\n2) 每条原则下记录：是否违反 / 问题描述 / 严重程度(1-4)\n3) 按严重程度排序\n4) 给出具体修改建议（文案/布局/交互）\n5) 输出评估报告",
    outputTemplate:"【评估总览】得分：x/10\n【问题清单】\n| # | 原则 | 问题 | 严重度 | 位置 | 建议 |\n…\n【优先修复 Top5】…",
    quality:"十大原则逐条覆盖、严重度分级合理、建议具体可执行", boundary:"不替代真实用户测试；主观判断需标注\"评估者观点\""
  },
  { id:"S-0006", name:"设计规范与 Design Token 生成", type:"skill", value:"从品牌关键词或参考图快速生成完整的设计规范和 Token 体系", stage:"设计", tags:["视觉设计","设计规范","Design Token"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    github:"🔗 GitHub", skillsSh:"📦 skills.sh", installCmd:"npx skills add mastepanoski/claude-skills --skill ui-design-review",
    scene:"从零建立或统一产品的视觉规范体系",
    input:"【产品名称】…\n【品牌关键词】（如：专业、温暖、科技感）\n【产品类型】（B端/C端/App/Web）\n【参考品牌或风格】…\n【特殊要求】（无障碍/暗黑模式等）",
    steps:"1) 解析品牌关键词 → 视觉风格方向\n2) 生成颜色系统：主色/辅色/中性色/语义色，含完整色阶\n3) 生成字体系统：字体族/字号梯度/行高/字重\n4) 生成间距系统：4px 基准递增\n5) 生成圆角/阴影/动效 Token\n6) 输出 CSS 变量代码",
    outputTemplate:"【风格定义】…\n【颜色 Token】\n| Token | 值 | 用途 |\n…\n【字体 Token】…\n【间距 Token】…\n【CSS 变量代码】…\n【使用指南】…",
    quality:"Token 命名语义化、色彩对比度 ≥ 4.5:1（WCAG AA）、梯度完整", boundary:"不生成具体 UI 组件稿；品牌色需人工确认"
  },
  { id:"S-0007", name:"UI 组件规范审查与优化", type:"skill", value:"审查 UI 组件是否符合设计规范，输出不一致项和修复建议", stage:"评审/测试", tags:["视觉设计","组件","规范审查"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    github:"🔗 GitHub", skillsSh:"📦 skills.sh", installCmd:"npx skills add mastepanoski/claude-skills --skill ui-design-review",
    scene:"检查设计稿或前端实现是否与设计系统/规范保持一致",
    input:"【设计规范/Token 文档】…\n【待审查页面/组件描述】…\n【审查范围】（颜色/字体/间距/圆角/图标…）\n【优先级】（全量/核心页面）",
    steps:"1) 对照 Token 逐项检查：颜色值、字号、间距、圆角\n2) 标记不一致项：位置 + 现状 + 应为\n3) 检查响应式适配一致性\n4) 检查状态样式一致性（hover/active/disabled/error）\n5) 按严重度分级并给出修复建议",
    outputTemplate:"【审查总览】一致率：x%\n【不一致清单】\n| # | 组件/位置 | 属性 | 现状 | 应为 | 严重度 |\n…\n【优先修复建议】…",
    quality:"检查项完整、问题定位精确到组件+属性、修复建议可直接执行", boundary:"需提供设计规范作为基准；无规范时先用 S-0006 生成"
  },
  { id:"S-0008", name:"设计稿走查与开发还原度检查", type:"skill", value:"对比设计稿与前端实现，自动生成还原度差异清单", stage:"评审/测试", tags:["视觉设计","走查","还原度"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    github:"🔗 GitHub", skillsSh:"📦 skills.sh", installCmd:"npx skills add mastepanoski/claude-skills --skill ui-design-review",
    scene:"对比设计稿与实际开发实现的差异",
    input:"【设计稿截图/链接】…\n【前端实现截图/URL】…\n【对照规范/Token】…\n【重点检查区域】…",
    steps:"1) 像素级对比设计稿与实现\n2) 标注差异点：位置 + 设计值 + 实现值\n3) 分类（布局/颜色/字体/间距/交互/动效）\n4) 严重度标记（P0阻塞/P1重要/P2建议）\n5) 生成走查清单",
    outputTemplate:"【还原度总览】还原率：x%\n【差异清单】\n| # | 位置 | 类型 | 设计值 | 实现值 | 严重度 |\n…\n【优先修复项】…",
    quality:"差异精确到像素级 · 分类明确 · 修复优先级清晰", boundary:"需同时提供设计稿和实现截图/URL"
  },
  { id:"S-0009", name:"空状态与异常态设计方案", type:"skill", value:"系统化梳理产品中所有空状态和异常态场景，输出完整的设计方案", stage:"设计", tags:["交互设计","空状态","异常处理"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    github:"🔗 GitHub", skillsSh:"📦 skills.sh", installCmd:"npx skills add mastepanoski/claude-skills --skill don-norman-principles-audit",
    scene:"梳理产品中所有需要处理的空白和异常场景",
    input:"【产品页面清单】…\n【数据来源类型】…\n【用户操作流程】…",
    steps:"1) 场景枚举（首次/无数据/搜索无结果/网络异常/权限/加载失败）\n2) 每类设计引导文案和插图方向\n3) 交互建议（引导操作/重试/跳转）\n4) 视觉风格方案",
    outputTemplate:"【空状态场景清单】\n| 场景 | 页面 | 触发条件 | 文案 | 操作 |\n…\n【异常态处理方案】\n| 异常类型 | 处理策略 | 文案 | 降级方案 |\n…",
    quality:"场景覆盖全面 · 文案友好 · 交互可行 · 有行动引导", boundary:"复杂产品按模块分批输出"
  },
  { id:"S-0010", name:"产品配色方案生成与评估", type:"skill", value:"基于品牌调性和场景需求，生成科学的配色方案并评估可用性", stage:"设计", tags:["视觉设计","配色","色彩"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    github:"🔗 GitHub", skillsSh:"📦 skills.sh", installCmd:"npx skills add mastepanoski/claude-skills --skill ui-design-review",
    scene:"需要为产品选择或优化配色方案",
    input:"【品牌调性】…\n【行业类型】…\n【场景需求】…\n【参考竞品色彩】…",
    steps:"1) 解析品牌关键词 → 色彩方向\n2) 生成主色/辅色/中性色\n3) 语义色定义\n4) 对比度验证（WCAG AA/AAA）\n5) 暗黑模式色彩适配",
    outputTemplate:"【配色方案】\n| Token | 色值 | 用途 | 对比度 |\n…\n【色阶梯度】…\n【暗黑模式映射】…",
    quality:"色彩对比度达标 · 色板完整 · 适配亮暗模式", boundary:"品牌色需人工确认；屏幕色差需实机验证"
  },
  { id:"S-0011", name:"WCAG 无障碍合规审计", type:"skill", value:"基于 WCAG 2.1/2.2 标准进行完整的无障碍可访问性审计", stage:"评审/测试", tags:["交互设计","无障碍","WCAG","合规","可访问性"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    github:"🔗 GitHub", skillsSh:"📦 skills.sh", installCmd:"npx skills add mastepanoski/claude-skills --skill wcag-accessibility-audit",
    scene:"确保产品符合无障碍标准，覆盖 POUR 四大原则",
    input:"【产品/页面 URL】…\n【目标等级】（A/AA/AAA）\n【重点检查范围】…",
    steps:"1) 可感知检查\n2) 可操作检查\n3) 可理解检查\n4) 稳健性检查\n5) 生成合规报告 + 修复建议",
    outputTemplate:"【审计总览】合规等级：AA | 通过率：x%\n【问题清单】\n| # | WCAG条款 | 原则 | 问题 | 严重度 | 修复建议 |\n…\n【优先修复项 Top10】…",
    quality:"覆盖 POUR 四原则 · 标注 WCAG 条款号 · 修复优先级明确", boundary:"自动工具无法检测所有问题，需配合人工审查"
  },
  { id:"S-0012", name:"认知走查 Cognitive Walkthrough", type:"skill", value:"模拟新手用户认知过程，逐步分析任务完成中的可学习性问题", stage:"评审/测试", tags:["交互设计","可用性","认知走查","可学习性","任务分析"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    github:"🔗 GitHub", skillsSh:"📦 skills.sh", installCmd:"npx skills add mastepanoski/claude-skills --skill cognitive-walkthrough",
    scene:"评估界面对新手用户的友好度和可学习性",
    input:"【任务描述】…\n【用户画像】…\n【界面截图/原型】…\n【预期步骤】…",
    steps:"1) 定义用户和任务\n2) 分解为具体操作步骤\n3) 每步四问评估：\n   - 用户会尝试达成正确效果？\n   - 用户会注意到正确操作？\n   - 用户会将操作与期望关联？\n   - 操作后用户能看到进展？\n4) 标记卡点和困惑\n5) 输出走查报告",
    outputTemplate:"【走查总览】\n任务完成难度：高/中/低\n关键卡点数：X\n\n【逐步分析】\n| 步骤 | 操作 | Q1 | Q2 | Q3 | Q4 | 卡点 | 建议 |\n…\n【优化建议（按优先级）】…",
    quality:"认知四问逐步覆盖 · 卡点定位精确 · 改进建议具体", boundary:"基于模拟认知，需真实用户测试验证"
  },
  { id:"S-0013", name:"Don Norman 设计原则审计", type:"skill", value:"基于《设计心理学》7 大原则评估界面设计", stage:"评审/测试", tags:["交互设计","设计原则","可用性","人性化设计","诺曼门"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    github:"🔗 GitHub", skillsSh:"📦 skills.sh", installCmd:"npx skills add mastepanoski/claude-skills --skill don-norman-principles-audit",
    scene:"用设计心理学原则评估产品设计",
    input:"【产品/页面描述】…\n【目标用户】…\n【核心交互】…",
    steps:"1) 可发现性评估\n2) 功能可见性评估\n3) 示能评估\n4) 约束分析\n5) 映射评估\n6) 反馈评估\n7) 概念模型评审",
    outputTemplate:"【评估总览】得分：x/7\n【逐原则分析】\n| 原则 | 评分 | 问题 | 建议 |\n…\n【核心发现】…\n【优化路线图】…",
    quality:"七大原则逐条覆盖 · 结合具体案例 · 建议可操作", boundary:"理论分析，需结合实际用户数据"
  },
  { id:"S-0014", name:"微信小程序 UI/UX 设计", type:"skill", value:"面向微信小程序的 UI/UX 专业技能包", stage:"设计", tags:["交互设计","视觉设计","微信小程序","移动端","UX","Design Token"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    github:"CodeBuddy 官方 Skill 市场", skillsSh:"CodeBuddy Skill Store", installCmd:"CodeBuddy IDE 内置 -> 设置 -> Skill -> 搜索 wechat-miniprogram-ui-ux -> 安装",
    scene:"微信小程序界面设计，符合平台约束和原生体验",
    input:"【页面类型】（list/detail/form/dashboard/feed…）\n【用户目标】…\n【设计约束】…\n【参考小程序】…",
    steps:"步骤 1：需求理解 → 确认页面类型、用户目标\n步骤 2：反模式过滤 → 检查网页风格直接复制\n步骤 3：设计系统建立 → 色彩/字体/间距/动效\n步骤 4：小程序原生实现 → WXML+WXSS+rpx",
    outputTemplate:"【页面方案】布局结构 + 组件选型 + 交互逻辑\n\n【设计 Token】色彩/字体/间距/圆角\n\n【交付检查清单】\n✅ 页面目标清晰\n✅ 每个区域只有一个主操作\n✅ 移动端阅读节奏和点击舒适度\n✅ 处理加载、空态、错误态、权限态\n✅ 不与微信右上角胶囊冲突",
    quality:"符合微信设计规范 · 移动端优先 · 原生体验一致", boundary:"仅适用于微信小程序，非通用网页 UI；针对移动端窄视口优先"
  },
  { id:"S-0015", name:"海外网页适配审计 (Global Web Adapt)", type:"skill", value:"评估中文 UI 在英文/全球化后的文本溢出、截断、布局错位风险", stage:"设计", tags:["交互设计","视觉设计","国际化","海外适配","出海"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    github:"本地 Skill (无 GitHub 链接)", skillsSh:"global-web-adapt", installCmd:"@skill://global-web-adapt\n\n文件路径:\n/Users/anyong/CodeBuddy/Claw/skills/global-web-adapt/",
    scene:"产品出海时评估多语言适配风险",
    input:"【页面截图】…\n【中英文案对照】…\n【目标语言和市场】…",
    steps:"Step 1: 识别高风险组件\n🔴 高风险：按钮、Tab标签、导航栏标题、表格表头、标签/徽章\n🟡 中风险：表单标签、卡片标题、空状态文案\n🟢 低风险：正文段落、长描述文本\n\nStep 2: 计算文本膨胀率\n| 中文字符数 | 英文预估长度 | 膨胀率 |\n| 2 字 | 6-10 字符 | 150%-250% |\n| 4 字 | 10-18 字符 | 125%-225% |\n\nStep 3: 布局弹性检测\nStep 4: 生成审计报告",
    outputTemplate:"## 海外网页适配审计报告\n\n### 📋 基本信息\n- 审计页面 / 时间 / 风险等级\n\n### 📊 风险概览\n| 风险等级 | 组件数量 | 占比 |\n\n### 🔴 高风险问题清单\n- 位置 / 中英文对照 / 膨胀率 / 修复建议\n\n### 💡 设计优化建议\n### ✅ 检查清单",
    quality:"高风险组件均已识别 · 膨胀率准确 · 包含 CSS 级解决方案", boundary:"膨胀率为估算值 · 德语/俄语需单独评估 · 不替代专业本地化测试",
    example:"@skill://global-web-adapt\n帮我评估这个中文界面的英文适配风险 [附截图]\n\n@skill://global-web-adapt\n这个按钮写\"立即购买\"，英文版会不会太长？\n\n@skill://global-web-adapt\n我的 Tab 有：首页、发现、消息、我的，英文版怎么处理？"
  }
];

const prompts = [
  { id:"P-0001", name:"用户故事拆解与验收标准生成", type:"prompt", value:"将粗粒度需求拆解为标准用户故事 + 验收标准", stage:"调研/需求", tags:["交互设计","用户故事","需求"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    promptText:"你是一位资深交互设计师。请将以下需求拆解为用户故事，并为每个故事编写验收标准。\n\n要求：\n1) 用户故事格式：As a {角色}, I want to {行为}, so that {价值}\n2) 每个故事附带验收标准（Given-When-Then 格式）\n3) 标注优先级（P0/P1/P2）和故事点估算（1/2/3/5/8）\n4) 如果需求信息不足，列出\"待澄清问题\"\n5) 按功能模块分组\n\n用户角色：{user_role}\n\n需求描述：\n{requirement}",
    variables:"{requirement}=原始需求描述, {user_role}=目标用户角色", outputFormat:"用户故事列表 + 验收标准表格", tone:"结构化、可执行、开发友好", boundary:"不编造业务规则；不确定的逻辑标注\"待确认\"",
    exampleInput:"需求：用户需要在后台管理系统中批量导入商品数据",
    exampleOutput:"【用户故事】\nUS-1 [P0, 3pt] As a 运营人员, I want to 通过 Excel 批量上传商品, so that 减少逐条录入的时间成本\n验收标准：\n- Given 我在商品管理页, When 我点击\"批量导入\", Then 弹出上传弹窗支持 .xlsx/.csv\n…\n【待澄清问题】\n1. 导入失败的商品如何处理？",
    failCase:"需求太模糊时会产出泛化故事，建议先补充业务上下文"
  },
  { id:"P-0002", name:"界面交互文案优化", type:"prompt", value:"优化界面中的按钮、提示、错误信息等交互文案", stage:"设计", tags:["交互设计","文案","UX Writing"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    promptText:"你是一位 UX Writing 专家。请优化以下界面文案，使其更清晰、友好、可操作。\n\n优化原则：\n1) 简洁：每条文案尽量 ≤ 15 个中文字\n2) 可操作：按钮文案用\"动词+名词\"格式（如\"保存草稿\"而非\"保存\"）\n3) 友好：错误提示说明原因 + 给出解决方案\n4) 一致：相同操作使用统一措辞\n5) 输出格式：表格（原文案 | 优化后 | 优化理由 | 类型）\n\n产品调性：{product_tone}\n使用场景：{context}\n\n待优化文案：\n{ui_copy_list}",
    variables:"{ui_copy_list}=待优化文案列表, {product_tone}=产品调性, {context}=使用场景", outputFormat:"文案对照表 + 优化理由", tone:"简洁、友好、一致", boundary:"不使用恐吓性文案；不用技术术语",
    exampleInput:"按钮文案：确定、取消、提交\n提示文案：操作失败、数据错误、网络异常\n产品调性：专业但温暖",
    exampleOutput:"| 原文案 | 优化后 | 优化理由 | 类型 |\n| 确定 | 确认提交 | 明确操作结果 | 按钮 |\n| 操作失败 | 提交未成功，请稍后重试 | 告知原因+给出行动 | 错误提示 |",
    failCase:"文案脱离上下文容易优化过度，建议附带截图或页面描述"
  },
  { id:"P-0003", name:"竞品交互分析报告", type:"prompt", value:"系统分析竞品的交互设计模式，提取可借鉴点", stage:"调研/需求", tags:["交互设计","竞品分析","调研"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    promptText:"你是一位资深交互设计师，擅长竞品分析。请对以下竞品进行交互设计维度的系统分析。\n\n分析框架：\n1) 信息架构：导航结构、层级深度、分类逻辑\n2) 核心流程：关键任务的步骤数和操作路径\n3) 交互模式：使用了哪些设计模式（搜索/筛选/排序/拖拽等）\n4) 特色功能：差异化的交互创新点\n5) 体验问题：明显的可用性问题\n\n输出要求：\n- 竞品对比矩阵（表格形式）\n- 每个竞品的亮点和不足\n- 对我方产品的可借鉴建议（按优先级排序）\n- 标注\"已验证\"或\"推测\"\n\n我方产品：{our_product}\n竞品列表：{competitors}\n重点分析维度：{analysis_dimensions}",
    variables:"{competitors}=竞品名称列表, {analysis_dimensions}=分析维度, {our_product}=我方产品", outputFormat:"竞品对比表格 + 可借鉴建议", tone:"客观、结构化、有依据", boundary:"不做主观优劣评价；标注信息来源和时效性",
    exampleInput:"竞品：飞书、钉钉、企业微信\n分析维度：即时通讯、日程管理\n我方产品：企业协同办公工具",
    exampleOutput:"【竞品对比矩阵】\n| 维度 | 飞书 | 钉钉 | 企微 |\n…\n【可借鉴建议】\n1. [P0] 飞书的消息分类体验值得借鉴…",
    failCase:"信息可能过时，建议标注分析日期并定期更新"
  },
  { id:"P-0004", name:"页面视觉优化建议", type:"prompt", value:"对现有页面进行视觉层面的诊断和优化建议", stage:"设计", tags:["视觉设计","优化","审查"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    promptText:"你是一位资深视觉设计师。请对以下页面进行视觉设计诊断，找出问题并给出优化建议。\n\n诊断维度：\n1) 视觉层级：信息主次是否清晰，视觉动线是否合理\n2) 一致性：颜色/字体/间距是否统一，是否符合设计规范\n3) 留白与呼吸感：布局是否拥挤，间距是否合理\n4) 色彩运用：配色协调性、对比度、语义正确性\n5) 字体排版：字号梯度、行高、对齐方式\n6) 图标与图形：风格统一性、大小一致性\n7) 响应式：不同尺寸下的视觉表现\n\n输出格式：\n- 问题清单表格（问题 | 维度 | 严重度 | 位置 | 优化建议）\n- 优先修复建议 Top5\n\n页面描述：\n{page_description}\n\n设计规范：{design_system}\n已知问题：{issues}",
    variables:"{page_description}=页面描述, {design_system}=设计规范(可选), {issues}=已知问题(可选)", outputFormat:"问题清单 + 优化建议表格", tone:"专业、客观、可执行", boundary:"基于设计原则，非个人审美偏好",
    exampleInput:"页面描述：某B端后台的数据看板页面，含 4 个数据卡片 + 1 个折线图 + 1 个数据表格",
    exampleOutput:"【问题清单】\n| 问题 | 维度 | 严重度 | 位置 | 建议 |\n| 数据卡片间距不一致 | 一致性 | P1 | 顶部卡片区 | 统一为 16px |",
    failCase:"没有截图时描述越详细越好，可用 HTML/CSS 代码补充"
  },
  { id:"P-0005", name:"图标体系规范与清单", type:"prompt", value:"为产品梳理完整的图标体系规范和需求清单", stage:"设计", tags:["视觉设计","图标","规范"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    promptText:"你是一位视觉设计系统专家。请为以下产品梳理完整的图标体系规范和需求清单。\n\n输出内容：\n1) 图标风格规范\n   - 风格定义（线性/面性/双色等）\n   - 网格系统（尺寸基准、安全区域、笔画粗细）\n   - 圆角规则\n   - 颜色规则（单色/多色、语义色使用）\n2) 尺寸规范\n   - 标准尺寸梯度（如 16/20/24/32/48px）\n   - 各尺寸适用场景\n3) 图标需求清单\n   - 按模块列出所有需要的图标\n   - 格式：| 图标名 | 模块 | 尺寸 | 状态数 | 描述 |\n4) 命名规范\n   - 命名规则和示例\n\n产品信息：{product_info}\n期望风格：{icon_style}\n页面/功能列表：{pages}",
    variables:"{product_info}=产品信息, {icon_style}=期望风格, {pages}=页面功能列表", outputFormat:"图标规范文档 + 需求清单", tone:"系统化、规范化", boundary:"不生成实际图标文件；仅输出规范和清单",
    exampleInput:"产品：电商后台管理系统\n风格：线性图标，2px 描边\n页面：首页看板、商品管理、订单管理、用户管理、设置",
    exampleOutput:"【图标风格规范】\n网格：24x24px 基准，2px 安全区，2px 描边\n…\n【图标清单】\n| 图标名 | 模块 | 尺寸 | 状态 | 描述 |\n| ic_dashboard | 首页 | 24px | 2(默认/选中) | 看板导航图标 |",
    failCase:"功能列表越详细，图标清单越准确"
  },
  { id:"P-0006", name:"深色模式适配方案", type:"prompt", value:"基于现有浅色设计，生成完整的深色模式适配规则和色值映射", stage:"设计", tags:["视觉设计","深色模式","适配"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    promptText:"你是一位精通深色模式设计的视觉设计师。请基于以下浅色模式设计 Token，生成完整的深色模式适配方案。\n\n适配原则：\n1) 不是简单反色，而是重新设计视觉层级\n2) 背景：使用深灰（#121212~#1E1E1E）而非纯黑\n3) 文字：降低白色亮度到 87%/60%/38% 三级\n4) 品牌色：适当提亮以保证可见性\n5) 阴影：用更深的颜色替代，或改用发光效果\n6) 图片/插图：降低亮度或加暗色蒙层\n\n输出格式：\n1) 色值映射表：| Token | 浅色值 | 深色值 | 说明 |\n2) 层级系统：背景层级（Surface 0-5）\n3) 文字层级：主要/次要/禁用\n4) 特殊处理：品牌色/语义色/图表色的调整规则\n5) 组件级适配备注\n\n浅色 Token：{light_tokens}\n品牌色：{brand_color}\n关键组件：{components}",
    variables:"{light_tokens}=浅色 Token/色值, {components}=关键组件, {brand_color}=品牌色", outputFormat:"深色模式完整色值映射 + 适配规则", tone:"系统化、可落地", boundary:"需在真实深色环境校验；OLED 屏幕需测试纯黑背景",
    exampleInput:"浅色Token：背景#FFFFFF，主文字#1A1A1A，品牌色#1677FF\n组件：按钮、卡片、输入框、表格、导航栏",
    exampleOutput:"【色值映射】\n| Token | 浅色 | 深色 | 说明 |\n| bg-primary | #FFFFFF | #1E1E1E | 主背景 |\n| text-primary | #1A1A1A | rgba(255,255,255,0.87) | 主文字 |",
    failCase:"缺少完整 Token 时先生成核心色值，后续补全"
  },
  { id:"P-0007", name:"复杂表单交互设计方案", type:"prompt", value:"为复杂表单设计合理的布局、校验规则、分步逻辑和错误处理", stage:"设计", tags:["交互设计","表单","表单设计"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    promptText:"你是一位擅长表单设计的交互设计师。请为以下复杂表单设计完整的交互方案。\n\n设计维度：\n1) 信息分组与排序：按用户填写心理顺序分组\n2) 分步策略：字段 > 7 个时建议分步，给出分步方案\n3) 字段交互：每个字段的控件类型、占位符、帮助文本\n4) 校验规则：实时校验 vs 提交校验、错误提示文案\n5) 联动逻辑：字段间的显示/隐藏/联动关系\n6) 默认值策略：智能预填、记住上次输入\n7) 防错设计：二次确认、撤销、自动保存\n8) 提交反馈：加载态、成功态、部分失败处理\n\n输出格式：\n- 分组方案 + 字段明细表格\n- 校验规则表格\n- 联动逻辑说明\n- 异常处理清单\n\n表单字段：{form_fields}\n业务规则：{business_rules}\n用户场景：{user_context}",
    variables:"{form_fields}=表单字段列表, {business_rules}=业务规则, {user_context}=用户场景", outputFormat:"表单设计方案文档", tone:"用户友好、减少认知负担", boundary:"不做视觉高保真稿；涉及隐私字段需提示合规",
    exampleInput:"字段：姓名、手机号、邮箱、公司名、部门、职位、地址（省市区街道）、备注\n场景：B端客户注册表单",
    exampleOutput:"【分组方案】\nStep1 基本信息：姓名+手机+邮箱\nStep2 公司信息：公司+部门+职位\nStep3 联系地址：省市区+街道+备注\n【字段明细】\n| 字段 | 控件 | 必填 | 校验规则 | 错误提示 |",
    failCase:"字段列表不完整时先列出已知字段，标注\"可能遗漏\""
  },
  { id:"P-0008", name:"响应式布局断点与适配方案", type:"prompt", value:"为产品设计完整的响应式断点规则和各尺寸布局适配方案", stage:"设计", tags:["视觉设计","响应式","布局"], status:"可用", version:"v1.0", maintainer:"anyong", updated:"2026-04",
    promptText:"你是一位精通响应式设计的视觉设计师。请为以下页面设计完整的响应式适配方案。\n\n输出内容：\n1) 断点定义\n   - 各断点像素值和对应设备类型\n   - 推荐：Mobile(<768) / Tablet(768-1024) / Desktop(1025-1440) / Wide(>1440)\n2) 栅格系统\n   - 列数、槽宽、边距在各断点下的值\n3) 各断点布局方案\n   - 核心组件在不同断点的排列方式（并排→堆叠等）\n   - 文字大小缩放规则\n   - 图片/媒体适配策略\n   - 隐藏/折叠策略\n4) 关键组件适配明细\n   - 导航：横向→汉堡菜单\n   - 表格：横滑/折叠/卡片化\n   - 表单：单列/双列切换\n5) 实现建议（CSS 要点）\n\n页面布局：{page_layout}\n目标设备：{target_devices}\n关键组件：{key_components}",
    variables:"{page_layout}=页面布局描述, {target_devices}=目标设备, {key_components}=关键组件", outputFormat:"响应式方案文档 + 各断点布局说明", tone:"系统化、有具体数值、可开发落地", boundary:"需在真实设备上验证；极端尺寸需做压力测试",
    exampleInput:"页面：数据管理后台，含顶部导航+侧边栏+内容区(表格+图表)\n设备：PC为主，iPad偶尔使用\n组件：数据表格、筛选栏、图表面板",
    exampleOutput:"【断点定义】\n| 断点 | 范围 | 列数 | 槽宽 | 边距 |\n| Desktop | 1025-1440px | 12列 | 24px | 32px |\n…\n【表格适配】Desktop:完整表格 → Tablet:隐藏次要列+横滑",
    failCase:"组件描述越具体越好；建议附带当前布局的线框描述"
  }
];
